accounts/api/urls.py
from django.conf.urls import url

from accounts.api.views import UserList

account_urls = [
    url(r'^active/$', UserList.as_view(), name='user-list'),
]

accounts/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^register', 'accounts.views.register', name='register'),
    url(r'^login', 'accounts.views.login', name='login'),
]

rps/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from rps.api.urls import api_urls
from socketio import sdjango

sdjango.autodiscover()

urlpatterns = [
    url(r'^$', 'rps.views.index', name='index'),
    url(r'^socket\.io', include(sdjango.urls)),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^games/', include('game.urls', namespace='games')),

    url(r'^api/', include(api_urls, namespace='api')),
]

accounts/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, \
    BaseUserManager


class CustomUserManager(BaseUserManager):
    def _create_user(self, username, password, is_staff, is_superuser,
                     **extra_fields):
        """
        Creates and saves a User with the given username and password.
        """
        now = timezone.now()
        if not username:
            raise ValueError('The given username must be set')
        user = self.model(is_staff=is_staff, is_superuser=is_superuser,
                          last_login=now, last_active=now, date_joined=now,
                          username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, password=None, **extra_fields):
        return self._create_user(
            username, password, False, False, **extra_fields)

    def create_superuser(self, username, password, **extra_fields):
        return self._create_user(
            username, password, True, True, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    Custom User model with admin-compliant permission.
    Username and password are required. Other fields are optional.
    """
    username = models.CharField(
        _('username'), max_length=255, unique=True)
    is_staff = models.BooleanField(
        _('staff status'), default=False,
        help_text=_('Designates whether the user can log into this admin '
                    'site.'))
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    quit_at = models.DateTimeField(_('quit at'), null=True, blank=True)
    last_active = models.DateTimeField(_('last active'), null=True, blank=True)
    socket_session_id = models.CharField(
        _('socket session id'), null=True, blank=True, max_length=30)

    objects = CustomUserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        return self.username

    def get_short_name(self):
        return self.username

    def __unicode__(self):
        return self.get_full_name()

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.utils.translation import ugettext_lazy as _


class UserCreationForm(forms.ModelForm):
    """
    A form that creates a user, with no privileges, from the given username and
    password.
    """
    error_messages = {
        'duplicate_username': _("A user with that username already exists."),
    }
    username = forms.CharField(label=_("Username"), widget=forms.TextInput(
        attrs={'placeholder': 'Username', 'required': True,
               'class': 'form-control'}))
    password = forms.CharField(
        label=_("Password"), widget=forms.PasswordInput(
            attrs={'placeholder': 'Password', 'required': True,
                   'class': 'form-control'}))

    class Meta:
        model = get_user_model()
        fields = ("username", "password")

    def clean_username(self):
        # Since CustomUser.username is unique, this check is redundant,
        # but it sets a nicer error message than the ORM. See #13147.
        username = self.cleaned_data["username"]
        try:
            get_user_model()._default_manager.get(username=username)
        except get_user_model().DoesNotExist:
            return username
        raise forms.ValidationError(
            self.error_messages['duplicate_username'],
            code='duplicate_username',
        )

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

accounts/api/views.py
from rest_framework import generics

from datetime import timedelta
from django.utils import timezone

from accounts.api.serializer import UserSerializer
from accounts.models import User


class UserList(generics.ListCreateAPIView):
    last_ten_minutes = timezone.now() - timedelta(minutes=10)
    queryset = User.objects.filter(last_active__gte=last_ten_minutes)
    serializer_class = UserSerializer

accounts/views.py
from django.contrib import auth
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render

from accounts.forms import UserCreationForm


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            user = auth.authenticate(username=request.POST['username'],
                                     password=request.POST['password'])
            auth.login(request, user)
            return HttpResponseRedirect(reverse('index'))
    else:
        form = UserCreationForm()

    return render(request, 'accounts/register.html', {'form': form})


def login(request):
    context = dict()

    if request.method == 'POST':
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        context['next'] = request.POST.get('next', '/')

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return HttpResponseRedirect(context['next'])
        else:
            context['error'] = 'Incorrect username or password'
    else:
        context['next'] = request.GET.get('next', '/')

    return render(request, 'accounts/login.html', context)

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}
    {{ block.super }} | Login
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-4 col-centered text-center">
            {% if error %}
                {{ error }}
            {% endif %}

             <form action="{% url 'accounts:login' %}" method="post" role="form">
                {% csrf_token %}

                <div class="form-group">
                    <label>Username</label>
                    <input type="text" name="username" placeholder="Username" required class="form-control">
                </div>

                <div class="form-group">
                    <label>Password</label>
                    <input type="password" name="password" placeholder="Password" required class="form-control">
                </div>

                <input type="hidden" name="next" value="{{ next }}"/>

                <div class="text-center">
                    <a href="{% url 'accounts:register' %}" class="btn dark">Register</a>
                    <button type="submit" class="btn btn-default">Login</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block title %}
    {{ block.super }} | Register
{% endblock %}

{% block content %}
    <form action="{% url 'accounts:register' %}" method="post" class="col-md-4 col-centered text-center">
        {% csrf_token %}
        {{ form }}

        <br>
        <div class="text-center">
            <button type="submit" class="btn btn-default">Register</button>
        </div>
    </form>
{% endblock %}